export const CHEFS = [
    {
        id: 1,
        name: "Chef Rafiq Ahmed",
        cuisineSpeciality: "Bengali",
        experience: "12 years",
        speciality: "Large parties & Weddings",
        rating: 4.9,
        pricePerSession: 2500,
    },
    {
        id: 2,
        name: "Chef Maria Gomez",
        cuisineSpeciality: "Italian",
        experience: "7 years",
        speciality: "Fine Dining & Fresh Pasta",
        rating: 4.8,
        pricePerSession: 2200,
    },
    {
        id: 3,
        name: "Chef Tanveer Hasan",
        cuisineSpeciality: "Continental",
        experience: "5 years",
        speciality: "Keto & Dietary Restrictions",
        rating: 4.6,
        pricePerSession: 1500,
    },
    {
        id: 4,
        name: "Chef Sumaiya Khan",
        cuisineSpeciality: "Bengali",
        experience: "8 years",
        speciality: "Traditional Seafood",
        rating: 4.7,
        pricePerSession: 1800,
    },
    {
        id: 5,
        name: "Chef Marco Rossi",
        cuisineSpeciality: "Italian",
        experience: "15 years",
        speciality: "Gourmet Wine Pairing",
        rating: 5.0,
        pricePerSession: 3500,
    },
    {
        id: 6,
        name: "Chef David Miller",
        cuisineSpeciality: "Continental",
        experience: "10 years",
        speciality: "Steakhouse Mastery",
        rating: 4.8,
        pricePerSession: 2800,
    },
    {
        id: 7,
        name: "Chef Anisul Hoque",
        cuisineSpeciality: "BBQ",
        experience: "6 years",
        speciality: "Outdoor Grilling",
        rating: 4.5,
        pricePerSession: 1600,
    },
    {
        id: 8,
        name: "Chef Li Wei",
        cuisineSpeciality: "Chinese",
        experience: "9 years",
        speciality: "Szechuan & Dim Sum",
        rating: 4.7,
        pricePerSession: 2000,
    },
    {
        id: 9,
        name: "Chef Farhana Islam",
        cuisineSpeciality: "Bengali",
        experience: "4 years",
        speciality: "Vegan & Plant-Based",
        rating: 4.4,
        pricePerSession: 1200,
    },
    {
        id: 10,
        name: "Chef Jean-Luc",
        cuisineSpeciality: "Continental",
        experience: "20 years",
        speciality: "French Fine Dining",
        rating: 4.9,
        pricePerSession: 4000,
    },
    {
        id: 11,
        name: "Chef Rahul Das",
        cuisineSpeciality: "Chinese",
        experience: "5 years",
        speciality: "Indo-Chinese Fusion",
        rating: 4.6,
        pricePerSession: 1400,
    },
    {
        id: 12,
        name: "Chef Sarah Jenkins",
        cuisineSpeciality: "Italian",
        experience: "8 years",
        speciality: "Gluten-Free Italian",
        rating: 4.7,
        pricePerSession: 1900,
    },
    {
        id: 13,
        name: "Chef Kabir Uddin",
        cuisineSpeciality: "Bengali",
        experience: "25 years",
        speciality: "Heritage Rezala & Biryani",
        rating: 5.0,
        pricePerSession: 3000,
    },
    {
        id: 14,
        name: "Chef Elena Petrova",
        cuisineSpeciality: "Continental",
        experience: "6 years",
        speciality: "Pastry & Dessert Table",
        rating: 4.8,
        pricePerSession: 2100,
    },
    {
        id: 15,
        name: "Chef Zhang Wei",
        cuisineSpeciality: "Chinese",
        experience: "11 years",
        speciality: "Traditional Cantonese",
        rating: 4.6,
        pricePerSession: 2300,
    },
    {
        id: 16,
        name: "Chef Mustafizur R.",
        cuisineSpeciality: "BBQ",
        experience: "4 years",
        speciality: "Budget Party Catering",
        rating: 4.3,
        pricePerSession: 1000,
    },
    {
        id: 17,
        name: "Chef Isabella Conti",
        cuisineSpeciality: "Italian",
        experience: "10 years",
        speciality: "Corporate Lunch Events",
        rating: 4.7,
        pricePerSession: 2400,
    },
    {
        id: 18,
        name: "Chef Nafisa Ali",
        cuisineSpeciality: "Bengali",
        experience: "7 years",
        speciality: "Post-Natal & Healthy Diets",
        rating: 4.9,
        pricePerSession: 1700,
    },
];
export const CUISINES = ["Bengali", "Chinese", "Italian", "Continental", "BBQ"];
export const DISH_ICONS = ["🍛", "🍜", "🍝", "🥩", "🍖"];
export const MEAL_TYPES = ["Breakfast", "Lunch", "Dinner", "Party catering"];
export const GUEST_OPTIONS = ["1–5", "6–15", "16–30", "30+"];
export const BUDGET_OPTIONS = [
    "৳500–৳1,000",
    "৳1,000–৳2,000",
    "৳2,000–৳5,000",
    "৳5,000+",
];
